services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx_web
    ports:
      - "8080:80"
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: php_fpm/Dockerfile
    container_name: php
    environment:
      DB_HOST: db
      DB_NAME: db
      DB_USER: bkfast
      DB_PASS: bekfast

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: bkfast
      POSTGRES_PASSWORD: bekfast
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backup:
    image: alpine
    container_name: postgres_backup
    depends_on:
      - db
    volumes:
      - ./db_backups:/backups:Z
    entrypoint: >
      sh -c "
      apk add --no-cache postgresql-client &&
      while true; do
        pg_dump -h db -U bkfast db | gzip > /backups/db_$(date +%F_%H-%M).sql.gz;
        echo 'âœ” Backup complete at' $(date);
        sleep 604800; # 7 * 24 hours
      done
      "
    environment:
      PGPASSWORD: bekfast

volumes:
  postgres_data:
